language: erlang

env:
  global:
    - "ARTIFACTS_AWS_REGION=ap-southeast-2"
    - "ARTIFACTS_S3_BUCKET=levelup-sydney"
    - secure: "ICvMhDyZB6mFvDjH6kIOhWEja/yQvqkmxrh4XPEuilaxWSGtaK/sJkpi5RNkeQzsF4HiwzXPa6h6J6vK8Of8DObyqJDHv0PPYPL11NZdXbKh2TW3iAUT9VB4bBG+0hhpEAninTG8w9EHdIrc7c1Rt/++oXk0RaoC5Dq4GOboZdE="
    - secure: "Gd6CUi7FMe4exmc1b4eOdogjczFlts7zbvorJPgCKrUfjneOaFd1+dgdwA9hmYoyEhzS045bHvpeMP5yyJfS8xEMdHaaLTtD9NC3TJm8W8WJn6fGdNahhQIVnp/NPhmiksIlUuuFK2t4ZC0c1mzs9l1bArKDXZN65pNRVADJcwA="
  matrix:
    - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

before_script:
  - "gem install --version 0.8.9 faraday"
  - "gem install travis-artifacts"

script:
  - busted spec
  - "./build.sh $TRAVIS_BUILD_NUMBER"

after_success:
  - "cd dist && travis-artifacts upload --path windows-levelup.zip --path LevelUp.app.tar.gz --path levelup.love --target-path ci/$TRAVIS_REPO_SLUG/build-$TRAVIS_BUILD_NUMBER --clone-path ci/$TRAVIS_REPO_SLUG/latest"
